python ConverteJAVA1.py Doloroso1.html misterioString.java 
python ConverteJAVA1.py Doloroso2.html misterioString.java 
python ConverteJAVA1.py Doloroso3.html misterioString.java 
python ConverteJAVA1.py Doloroso4.html misterioString.java 
python ConverteJAVA1.py Doloroso5.html misterioString.java 
python ConverteJAVA1.py Glorioso1.html misterioString.java 
python ConverteJAVA1.py Glorioso2.html misterioString.java 
python ConverteJAVA1.py Glorioso3.html misterioString.java 
python ConverteJAVA1.py Glorioso4.html misterioString.java 
python ConverteJAVA1.py Glorioso5.html misterioString.java 
python ConverteJAVA1.py Luminoso1.html misterioString.java 
python ConverteJAVA1.py Luminoso2.html misterioString.java 
python ConverteJAVA1.py Luminoso3.html misterioString.java 
python ConverteJAVA1.py Luminoso4.html misterioString.java 
python ConverteJAVA1.py Luminoso5.html misterioString.java 
